### ISSUE TITLE
Anonymous function exception

### ISSUE THREAD

**Issue by imyawar** [sindresorhus/gulp-template#12]
I am getting error while executing following

var gulp = require('gulp');
var template = require('gulp-template');

gulp.task('default', function () {
    return gulp.src('src/greeting.html')
        .pipe(template({name: 'Sindre'}))
        .pipe(gulp.dest('dist'));
});

It was all working fine until I introduced lodash as dependency, removed node_modules folder and executed “npm install”. It seems like conflict in dependencies. Can you please provide me the clue?
# Error appeared

events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: Unexpected token =
    at Function (<anonymous>)
    at template (/node_modules/lodash/dist/lodash.js:6305:22)
    at DestroyableTransform._transform (/node_modules/gulp-template/index.js:24:31)
    at DestroyableTransform.Transform._read (/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
# Content of package.json

"dependencies": {
    "bibtex-parser": "^0.0.x",
    "bluebird": "^2.2.2",
    "latex": "^0.0.x",
    "lodash": "^2.4.1",
    "lunr": "^0.5.x",
    "node-read": "^0.1.4",
    "xml2js": "^0.4.x",
    "xmldom": "^0.1.x",
    "xpath.js": "^0.0.x"
  },
"devDependencies": {
    "nlf": "^1.0.2",
    "del": "^0.1.1",
    "gulp": "^3.8.5",
    "gulp-bower": "^0.0.6",
    "gulp-autoprefixer": "^0.0.8",
    "gulp-cache": "^0.2.0",
    "gulp-changed": "^0.4.0",
    "gulp-load-plugins": "^0.5.3",
    "gulp-ruby-sass": "^0.5.0",
    "gulp-size": "^0.4.0",
    "gulp-uglify": "^0.3.1",
    "gulp-browserify": "^0.2.0",
    "gulp-compass": "^1.1.9",
    "gulp-rename": "^1.2.0",
    "gulp-template": "^1.0.0",
    "gulp-entity-convert": "^0.0.1",
    "require-dir": "^0.1.0",
    "run-sequence": "^0.3.6",
    "browser-sync": "^1.1.2",
    "gulp-util": "^3.0.0",
    "node-webkit-builder": "^0.1.1",
    "config": "^1.0.0"
  }

**Comment by goldcaddy77** [comment]
For anybody else with this error, mine was simply a parsing error in the template:

```
{
  "name": "<% =componentKey %>",
  "version": "0.0.0",
  "dependencies": {}
}
```

Changing this to `"<%= componentKey %>"` fixed the issue.
