### ISSUE TITLE
Gulp task crashes when I'm trying to copy fnt file through gulp-template

### ISSUE THREAD

**Issue by zhouhao27** [sindresorhus/gulp-template#28]
Here is my gulp file:

    gulp.task('assets', function() {	
		return gulp.src(srcs.assets)
			.pipe(changed(dests.assets))
			.pipe(gulp.dest(dests.assets))
			.pipe(browserSync.reload({stream : true}));
	});

Basically it just copy assets folder to my build folder. The structure of assets folder is:

> assets --
>            |--- images
>            |--- sounds
>            |--- fonts

There is no problem if I remove the fonts folder. But I got the following error message when I added the fonts folder with the .fnt file. 

> events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: Unexpected token <
    at Function (native)
    at template (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp-template/node_modules/lodash/dist/lodash.js:6306:22)
    at Transform._transform (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp-template/index.js:19:31)
    at Transform._read (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp-template/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/local/lib/node_modules/slush-phaser-typescript-scss/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

The fnt file is:

	<font>
	  <info face="font" size="72" bold="0" italic="0" charset="" unicode="" stretchH="100" smooth="1" aa="1" padding="2,2,2,2" spacing="0,0" outline="0"/>
	  <common lineHeight="80" base="57" scaleW="361" scaleH="512" pages="1" packed="0"/>
	  <pages>
	    <page id="0" file="font.png"/>
	  </pages>
	  <chars count="80">
	    <char id="32" x="0" y="0" width="0" height="0" xoffset="1" yoffset="5" xadvance="20" page="0" chnl="15"/>
	  </chars>
	  <kernings count="96">
	    <kerning first="32" second="65" amount="-4"/>
	    <kerning first="121" second="46" amount="-5"/>
	  </kernings>
	</font>

Can anybody suggest what's wrong with my fnt file? Thanks.

**Comment by sindresorhus** [comment]
You can't just pass random files through. You have to filter out the actual template files and pass them to this plugin. It chokes as it tries to parse the font file as a template.

**Comment by joaocc** [comment]
We are also facing a similar issue. What would be needed to have gulp-template acting as a simply pass-through on files that don't have templates to expand?

**Comment by sindresorhus** [comment]
There's no way to detect that as you can configure any template syntax with Lodash/Underscore. Just use `gulp-filter` to filter out the correct files, or limit your `gulp.src` to just the template files.
