### ISSUE TITLE
error if gulp.src has negated paths

### ISSUE THREAD

**Issue by jaichandra** [sindresorhus/gulp-template#33]
Below code throws error:
```
gulp.src(['src/**/*.html', '!src/**/test/*.html'])
            .pipe(template({
                includes: '<script>....</script>'
            }))
            .pipe(gulp.dest(destination));
```

Error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
ReferenceError: data is not defined
    at eval (lodash.templateSources[5]:10:4)
    at DestroyableTransform._transform (/Users/.../node_modules/gulp-template/index.js:22:40)
    at DestroyableTransform.Transform._read (/Users/.../node_modules/gulp-template/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/.../node_modules/gulp-template/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/.../node_modules/gulp-template/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/.../node_modules/gulp-template/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/.../node_modules/gulp-template/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/.../node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/.../node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/.../node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)

```

**Comment by sindresorhus** [comment]
I don't think it's because of negated files. More likely it's not matching any files then. Try using https://github.com/sindresorhus/gulp-debug to see what files are passing through it.

**Comment by jaichandra** [comment]
@sindresorhus sorry about that. It was an issue with one of the files. Closing this.
